pwn:
    home: pwn/dict
yarn:
    xml: yarn/yarn.xml
gv:
    out: out2.dot
    threshold: 0.2
gr:
    threshold: 0.15
    maxEdges: 0
    depth: 2

imagenet:
  mapping_30_31: id-files/imagenet30-31.mapping.txt
  imagesDir: misc/imagenet

logging:
    config: file://${user.dir}/config/logback.xml
app:
    dictsXml: file://${user.dir}/config/dicts.xml
    alignmentStagesXml: file://${user.dir}/config/alignmentStages.xml
cs:
  tasks:
    b:
      dir: croudsourcing/taskB
    a:
      dir: croudsourcing/taskA
      aggr:
        tags: zencrowd
        threshold: 0.4
spring:
    jpa:
        database: POSTGRESQL
        show-sql: false
        hibernate:
          naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
          ddl-auto: none
    datasource:
        initialize: false
        platform: postgresql
        url: jdbc:postgresql://localhost:5432/yarn_pwn_alignment
        username: georgeee
        password: krispo
