pwn:
    home: pwn/dict
yarn:
    xml: yarn/yarn.xml
gv:
    out: out2.dot
gr:
    threshold: 0.2
    maxEdges: 25
    depth: 2

imagenet:
  mapping_30_31: id-files/imagenet30-31.mapping.txt
  imagesDir: misc/imagenet

app:
    dictXml: file://${user.dir}/config/dicts.xml

spring:
    jpa:
        database: POSTGRESQL
        show-sql: true
        hibernate:
          naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
          ddl-auto: none
    datasource:
        initialize: false
        platform: postgresql
        url: jdbc:postgresql://localhost:5432/yarn_pwn_alignment
        username: georgeee
        password: krispo
