pwn:
    home: pwn/dict
yarn:
    xml: yarn/yarn.xml
gv:
    out: out2.dot
    maxEdges: 10
gr:
    threshold: 0.2
    maxEdges: 25
    depth: 2

imagenet:
  mapping_30_31: id-files/imagenet30-31.mapping.txt
  imagesDir: misc/imagenet

app:
    dictXml: file://${user.dir}/config/dicts.xml

spring:
    datasource:
        initialize: false
    jpa:
        show-sql: true
        hibernate:
          ddl-auto: none
          naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
            hbm2ddl:
              auto: none
            temp:
              use_jdbc_metadata_defaults: false